import type { ApplicantProfile, CompanyProfile, JobPosting } from "./types";

export const hrJobs: JobPosting[] = [
  {
    id: "job-1",
    title: "Senior Frontend Developer",
    description: "Create polished product experiences with React, TypeScript, and design systems.",
    requiredSkills: ["React", "TypeScript", "UI/UX", "Performance Optimization"],
    experience: "Senior",
    type: "Full-time",
    location: "Cairo, Egypt",
    salaryRange: "EGP 18,000 - 24,000",
    deadline: "2026-07-10",
    status: "Active",
    applicants: 24,
    matchPercent: 91,
    postedAt: "2026-06-10",
  },
  {
    id: "job-2",
    title: "Product Designer",
    description: "Lead product design and collaborate with engineering to ship user-friendly experiences.",
    requiredSkills: ["Figma", "Design Systems", "User Research"],
    experience: "Mid-level",
    type: "Remote",
    location: "Remote",
    salaryRange: "EGP 14,000 - 18,000",
    deadline: "2026-07-04",
    status: "Awaiting Payment",
    applicants: 16,
    matchPercent: 76,
    postedAt: "2026-06-18",
  },
  {
    id: "job-3",
    title: "HR Operations Lead",
    description: "Manage hiring workflows, vendor partnerships, and candidate experience for growth teams.",
    requiredSkills: ["HR Tech", "Operations", "Communication"],
    experience: "Senior",
    type: "Full-time",
    location: "Alexandria, Egypt",
    salaryRange: "EGP 15,000 - 20,000",
    deadline: "2026-07-14",
    status: "Pending Review",
    applicants: 11,
    matchPercent: 67,
    postedAt: "2026-06-21",
  },
  {
    id: "job-4",
    title: "Junior Backend Engineer",
    description: "Build APIs and improve reliability for the matching engine and admin workflows.",
    requiredSkills: ["Node.js", "SQL", "REST APIs"],
    experience: "Junior",
    type: "Full-time",
    location: "Cairo, Egypt",
    salaryRange: "EGP 10,000 - 13,000",
    deadline: "2026-07-18",
    status: "Draft",
    applicants: 2,
    matchPercent: 0,
    postedAt: "2026-06-25",
  },
  {
    id: "job-5",
    title: "Employer Branding Specialist",
    description: "Develop employer campaigns and support candidate attraction for key accounts.",
    requiredSkills: ["Brand Strategy", "Content", "Analytics"],
    experience: "Mid-level",
    type: "Part-time",
    location: "Hybrid — Cairo",
    salaryRange: "EGP 8,000 - 12,000",
    deadline: "2026-07-08",
    status: "Rejected",
    applicants: 4,
    matchPercent: 54,
    postedAt: "2026-06-17",
  },
];

export const hrApplicants: ApplicantProfile[] = [
  {
    id: "applicant-1",
    name: "Farida El-Sayed",
    role: "Frontend Developer",
    company: "Mosaic Labs",
    matchScore: 93,
    experience: "5 years",
    status: "New",
    appliedDate: "2026-06-18",
    matchingSkills: ["React", "TypeScript", "Tailwind CSS"],
    missingSkills: ["GraphQL", "Design Systems"],
    coverLetter:
      "I’m excited to bring my frontend experience and passion for polished interfaces to your hiring platform.",
    cvFileName: "farida_elsayed_cv.pdf",
  },
  {
    id: "applicant-2",
    name: "Omar Naguib",
    role: "Product Designer",
    company: "Studio 47",
    matchScore: 87,
    experience: "4 years",
    status: "Shortlisted",
    appliedDate: "2026-06-19",
    matchingSkills: ["Figma", "Prototyping", "User Research"],
    missingSkills: ["Motion Design"],
    coverLetter:
      "I have built design systems for SaaS products and I am eager to support your candidate experience improvements.",
    cvFileName: "omar_naguib_cv.pdf",
  },
  {
    id: "applicant-3",
    name: "Yara Hassan",
    role: "HR Operations Lead",
    company: "TalentWave",
    matchScore: 80,
    experience: "6 years",
    status: "Rejected",
    appliedDate: "2026-06-20",
    matchingSkills: ["HR Tech", "Process Design"],
    missingSkills: ["Vendor Management", "Analytics"],
    coverLetter:
      "I specialize in closing operational gaps and improving recruitment workflows for fast-moving teams.",
    cvFileName: "yara_hassan_cv.pdf",
  },
  {
    id: "applicant-4",
    name: "Amir Adel",
    role: "Junior Backend Engineer",
    company: "PixelTree",
    matchScore: 75,
    experience: "2 years",
    status: "New",
    appliedDate: "2026-06-21",
    matchingSkills: ["Node.js", "SQL"],
    missingSkills: ["Testing", "API Security"],
    coverLetter:
      "I enjoy delivering reliable backend services and supporting scalable recruitment systems.",
    cvFileName: "amir_adel_cv.pdf",
  },
];

export const companyProfile: CompanyProfile = {
  name: "Masarak Talent",
  website: "https://masarak.ai",
  industry: "HR Technology",
  description:
    "Masarak Talent helps companies automate hiring with smarter candidate matching, streamlined workflows, and actionable analytics.",
};
