export type Job = {
  id: string;
  title: string;
  company: string;
  location: string;
  source: "LinkedIn" | "Indeed" | "Masarak" | "Wezzuf";
  matchScore: number;
  description: string;
  type: string;
  salary: number;
  postedAt: string;
  experience: string;
  field: "frontend" | "backend" | "flutter";
  missingSkills: string[];
};

export const frontendJobs: Job[] = [
  {
    id: "f1",
    title: "Senior React Developer",
    company: "Mosaic Labs",
    location: "Cairo, Egypt",
    source: "LinkedIn",
    matchScore: 92,
    description: "Develop and optimize complex React applications with TypeScript.",
    type: "Full-time",
    salary: 18000,
    postedAt: "2026-06-13",
    experience: "Senior",
    field: "frontend",
    missingSkills: ["TypeScript Advanced Patterns", "React Performance Optimization", "Unit Testing (Jest/RTL)"]
  },
  {
    id: "f2",
    title: "Frontend Engineer (React)",
    company: "NextBridge",
    location: "Remote",
    source: "Indeed",
    matchScore: 85,
    description: "Build UI components and reusable design systems.",
    type: "Remote",
    salary: 14500,
    postedAt: "2026-06-17",
    experience: "Mid-level",
    field: "frontend",
    missingSkills: ["TypeScript Generics", "Accessibility (a11y)", "GraphQL Client Integration"]
  },
  {
    id: "f3",
    title: "UI Developer",
    company: "Studio 47",
    location: "Giza, Egypt",
    source: "Masarak",
    matchScore: 78,
    description: "Translate designs into pixel-perfect interfaces.",
    type: "Full-time",
    salary: 12500,
    postedAt: "2026-06-11",
    experience: "Mid-level",
    field: "frontend",
    missingSkills: ["CSS Architecture (BEM/ITCSS)", "Responsive Layout Techniques", "Cross-browser Debugging"]
  },
  {
    id: "f4",
    title: "React Performance Engineer",
    company: "PixelTree",
    location: "Alexandria, Egypt",
    source: "LinkedIn",
    matchScore: 74,
    description: "Identify and fix rendering bottlenecks in large SPAs.",
    type: "Part-time",
    salary: 12000,
    postedAt: "2026-06-14",
    experience: "Mid-level",
    field: "frontend",
    missingSkills: ["React Memoization Patterns", "Code Splitting", "Performance Profiling"]
  },
  {
    id: "f5",
    title: "Frontend Consultant",
    company: "Crafted",
    location: "Remote",
    source: "Indeed",
    matchScore: 69,
    description: "Advise on frontend architecture and best practices.",
    type: "Freelance",
    salary: 14000,
    postedAt: "2026-06-09",
    experience: "Senior",
    field: "frontend",
    missingSkills: ["Design Systems", "TypeScript Refactoring", "Testing Strategy"]
  },
  {
    id: "f6",
    title: "React Native Frontend",
    company: "MobileWave",
    location: "Remote",
    source: "LinkedIn",
    matchScore: 76,
    description: "Build mobile interfaces using React Native.",
    type: "Remote",
    salary: 13000,
    postedAt: "2026-06-10",
    experience: "Mid-level",
    field: "frontend",
    missingSkills: ["React Native Navigation", "Platform-specific Styling", "Native Module Integration"]
  },
  {
    id: "f7",
    title: "Frontend Engineer - eCommerce",
    company: "Shoply",
    location: "Cairo, Egypt",
    source: "Wezzuf",
    matchScore: 71,
    description: "Improve conversion through fast, accessible frontend code.",
    type: "Full-time",
    salary: 11500,
    postedAt: "2026-06-08",
    experience: "Junior",
    field: "frontend",
    missingSkills: ["Core Web Vitals", "Client-side Caching", "A/B Testing Basics"]
  },
  {
    id: "f8",
    title: "Frontend Developer (Design Systems)",
    company: "Nova Systems",
    location: "Alexandria, Egypt",
    source: "Masarak",
    matchScore: 80,
    description: "Work on component libraries and tokens.",
    type: "Full-time",
    salary: 15000,
    postedAt: "2026-06-07",
    experience: "Mid-level",
    field: "frontend",
    missingSkills: ["CSS-in-JS Patterns", "Storybook Maintenance", "Tokenization"]
  },
  {
    id: "f9",
    title: "Senior Frontend Architect",
    company: "CoreTech",
    location: "Giza, Egypt",
    source: "LinkedIn",
    matchScore: 90,
    description: "Design frontend architecture for multi-team products.",
    type: "Full-time",
    salary: 20000,
    postedAt: "2026-06-05",
    experience: "Senior",
    field: "frontend",
    missingSkills: ["Microfrontends", "Monorepo Tooling", "Release Strategies"]
  },
  {
    id: "f10",
    title: "Junior Web Developer",
    company: "StartupHub",
    location: "Cairo, Egypt",
    source: "Wezzuf",
    matchScore: 60,
    description: "Work on frontend features under senior mentorship.",
    type: "Full-time",
    salary: 9500,
    postedAt: "2026-06-01",
    experience: "Junior",
    field: "frontend",
    missingSkills: ["Modern JavaScript (ES6+)", "Debugging Tools", "Version Control Workflows"]
  }
];

export const backendJobs: Job[] = [
  {
    id: "b1",
    title: "Senior Backend Engineer (Node.js)",
    company: "Eagle Analytics",
    location: "Cairo, Egypt",
    source: "Indeed",
    matchScore: 91,
    description: "Design resilient services and APIs for scale.",
    type: "Full-time",
    salary: 18500,
    postedAt: "2026-06-15",
    experience: "Senior",
    field: "backend",
    missingSkills: ["Microservices Design", "Distributed Tracing", "Circuit Breakers"]
  },
  {
    id: "b2",
    title: "API Developer (REST/GraphQL)",
    company: "Nova Systems",
    location: "Alexandria, Egypt",
    source: "Masarak",
    matchScore: 80,
    description: "Implement and document APIs with strong contracts.",
    type: "Full-time",
    salary: 13500,
    postedAt: "2026-06-08",
    experience: "Mid-level",
    field: "backend",
    missingSkills: ["API Versioning", "Auth & OAuth2", "Schema Design"]
  },
  {
    id: "b3",
    title: "Platform Engineer",
    company: "CloudOps",
    location: "Remote",
    source: "LinkedIn",
    matchScore: 86,
    description: "Build developer platforms and infra tooling.",
    type: "Remote",
    salary: 16000,
    postedAt: "2026-06-12",
    experience: "Mid-level",
    field: "backend",
    missingSkills: ["Kubernetes Patterns", "CI/CD Pipelines", "Observability (Prometheus)"]
  },
  {
    id: "b4",
    title: "Database Engineer",
    company: "DataWorks",
    location: "Cairo, Egypt",
    source: "Wezzuf",
    matchScore: 75,
    description: "Design schemas and optimize queries for OLTP systems.",
    type: "Full-time",
    salary: 14000,
    postedAt: "2026-06-10",
    experience: "Mid-level",
    field: "backend",
    missingSkills: ["Indexing Strategies", "Query Optimization", "Replication & Sharding"]
  },
  {
    id: "b5",
    title: "Backend Developer (Payments)",
    company: "PayCore",
    location: "Giza, Egypt",
    source: "Indeed",
    matchScore: 70,
    description: "Integrate payment providers and ensure compliance.",
    type: "Full-time",
    salary: 15000,
    postedAt: "2026-06-09",
    experience: "Mid-level",
    field: "backend",
    missingSkills: ["PCI-DSS Basics", "Idempotency", "Webhooks Handling"]
  },
  {
    id: "b6",
    title: "Backend QA Engineer",
    company: "TestLabs",
    location: "Cairo, Egypt",
    source: "Masarak",
    matchScore: 68,
    description: "Build integration tests and contract testing suites.",
    type: "Full-time",
    salary: 12000,
    postedAt: "2026-06-07",
    experience: "Junior",
    field: "backend",
    missingSkills: ["Contract Testing", "Integration Test Design", "Mocking External Services"]
  },
  {
    id: "b7",
    title: "Site Reliability Engineer",
    company: "CoreTech",
    location: "Remote",
    source: "LinkedIn",
    matchScore: 85,
    description: "Ensure high availability and incident response.",
    type: "Full-time",
    salary: 17000,
    postedAt: "2026-06-06",
    experience: "Senior",
    field: "backend",
    missingSkills: ["SLOs & SLIs", "Runbook Creation", "Chaos Engineering Basics"]
  },
  {
    id: "b8",
    title: "Backend Engineer (Go)",
    company: "GopherTech",
    location: "Alexandria, Egypt",
    source: "Wezzuf",
    matchScore: 77,
    description: "Build performant services using Go.",
    type: "Full-time",
    salary: 14500,
    postedAt: "2026-06-05",
    experience: "Mid-level",
    field: "backend",
    missingSkills: ["Concurrency Patterns", "Profiling & Benchmarks", "Memory Management"]
  },
  {
    id: "b9",
    title: "Junior Backend Developer",
    company: "StartupHub",
    location: "Cairo, Egypt",
    source: "Masarak",
    matchScore: 62,
    description: "Support backend teams and learn system design.",
    type: "Full-time",
    salary: 10000,
    postedAt: "2026-06-03",
    experience: "Junior",
    field: "backend",
    missingSkills: ["HTTP Fundamentals", "Database Transactions", "Basic Security Practices"]
  },
  {
    id: "b10",
    title: "Integration Engineer",
    company: "Linkers",
    location: "Giza, Egypt",
    source: "LinkedIn",
    matchScore: 73,
    description: "Connect third-party systems and maintain data flows.",
    type: "Full-time",
    salary: 13000,
    postedAt: "2026-06-01",
    experience: "Mid-level",
    field: "backend",
    missingSkills: ["ETL Basics", "Queueing Systems", "Data Mapping"]
  }
];

export const flutterJobs: Job[] = [
  {
    id: "fl1",
    title: "Flutter Engineer",
    company: "AppHouse",
    location: "Cairo, Egypt",
    source: "Wezzuf",
    matchScore: 84,
    description: "Build cross-platform mobile apps using Flutter.",
    type: "Full-time",
    salary: 14000,
    postedAt: "2026-06-12",
    experience: "Mid-level",
    field: "flutter",
    missingSkills: ["State Management (Provider/Bloc)", "Flutter Animations", "Platform Channels"]
  },
  {
    id: "fl2",
    title: "Senior Flutter Developer",
    company: "MobileWave",
    location: "Remote",
    source: "LinkedIn",
    matchScore: 88,
    description: "Lead mobile features and optimize performance.",
    type: "Remote",
    salary: 15500,
    postedAt: "2026-06-10",
    experience: "Senior",
    field: "flutter",
    missingSkills: ["Native Integrations", "Advanced State Management", "Testing (Widget/Integration)"]
  },
  {
    id: "fl3",
    title: "Cross-Platform Mobile Dev",
    company: "FlutterLab",
    location: "Giza, Egypt",
    source: "Masarak",
    matchScore: 78,
    description: "Ship performant apps across iOS and Android.",
    type: "Full-time",
    salary: 13000,
    postedAt: "2026-06-09",
    experience: "Mid-level",
    field: "flutter",
    missingSkills: ["Adaptive UI", "Platform Differences", "CI for Mobile"]
  },
  {
    id: "fl4",
    title: "Junior Flutter Developer",
    company: "StartApp",
    location: "Cairo, Egypt",
    source: "Indeed",
    matchScore: 66,
    description: "Work on mobile features and bug fixes.",
    type: "Full-time",
    salary: 10000,
    postedAt: "2026-06-08",
    experience: "Junior",
    field: "flutter",
    missingSkills: ["Dart Language Basics", "Widget Tree Optimization", "Device Testing"]
  },
  {
    id: "fl5",
    title: "Flutter UI Engineer",
    company: "Designly",
    location: "Alexandria, Egypt",
    source: "LinkedIn",
    matchScore: 73,
    description: "Implement complex UI and animations in Flutter.",
    type: "Full-time",
    salary: 12000,
    postedAt: "2026-06-06",
    experience: "Mid-level",
    field: "flutter",
    missingSkills: ["Implicit & Explicit Animations", "Custom Paint", "Performance Budgets"]
  },
  {
    id: "fl6",
    title: "Mobile Engineer (Flutter)",
    company: "NovaMob",
    location: "Remote",
    source: "Masarak",
    matchScore: 70,
    description: "Build end-to-end mobile experiences.",
    type: "Full-time",
    salary: 11500,
    postedAt: "2026-06-04",
    experience: "Mid-level",
    field: "flutter",
    missingSkills: ["Plugin Development", "App Lifecycle Management", "Secure Storage"]
  },
  {
    id: "fl7",
    title: "Flutter Performance Engineer",
    company: "PerfLabs",
    location: "Giza, Egypt",
    source: "Wezzuf",
    matchScore: 82,
    description: "Profile and optimize Flutter apps for smoothness.",
    type: "Full-time",
    salary: 14500,
    postedAt: "2026-06-02",
    experience: "Senior",
    field: "flutter",
    missingSkills: ["Skia Rendering", "Frame Scheduling", "Widget Rebuild Optimization"]
  },
  {
    id: "fl8",
    title: "Flutter Integrations Engineer",
    company: "LinkMobile",
    location: "Cairo, Egypt",
    source: "Indeed",
    matchScore: 76,
    description: "Integrate apps with backend services and SDKs.",
    type: "Full-time",
    salary: 12500,
    postedAt: "2026-05-30",
    experience: "Mid-level",
    field: "flutter",
    missingSkills: ["REST & GraphQL Integration", "Offline Sync Patterns", "Background Tasks"]
  },
  {
    id: "fl9",
    title: "Flutter Test Engineer",
    company: "TestMob",
    location: "Remote",
    source: "LinkedIn",
    matchScore: 68,
    description: "Write widget and integration tests for mobile apps.",
    type: "Remote",
    salary: 11000,
    postedAt: "2026-05-28",
    experience: "Junior",
    field: "flutter",
    missingSkills: ["Widget Testing", "Integration Flows", "Mocking Platform Channels"]
  },
  {
    id: "fl10",
    title: "Cross-platform Architect",
    company: "CrossTech",
    location: "Alexandria, Egypt",
    source: "Masarak",
    matchScore: 81,
    description: "Define mobile architecture and tech choices.",
    type: "Full-time",
    salary: 17000,
    postedAt: "2026-05-25",
    experience: "Senior",
    field: "flutter",
    missingSkills: ["Platform Strategy", "Modular App Design", "CI/CD for Mobile"]
  }
];

export const allPools = { frontend: frontendJobs, backend: backendJobs, flutter: flutterJobs };
